### ISSUE TITLE
wait_for_postgres_function isn't an actual function

### ISSUE THREAD

**Issue by ianfrantz** [smithjd/sql-pet#100]
**Describe the bug**
wait_for_postgres function isn't defined in 04-docker-setup

**To Reproduce**
1. Run file. 
2. con should fail.

**Expected behavior**
The function needs created:
HTML code has the old creation of this. 

It looks like John may have removed this on 9/28 but I'm not sure. 

#' Connect to Postgres, waiting if it is not ready
#'
#' @param user Username that will be found
#' @param password Password that corresponds to the username
#' @param dbname the name of the database in the database
#' @param seconds_to_test the number of iterations to try while waiting for Postgres to be ready
#' @export
wait_for_postgres <- function(user, password, dbname, seconds_to_test = 10) {
  for (i in 1:seconds_to_test) {
    db_ready <- DBI::dbCanConnect(RPostgres::Postgres(),
                                  host = "localhost",
                                  port = "5432",
                                  user = user,
                                  password = password,
                                  dbname = dbname)
    if ( !db_ready ) {Sys.sleep(1)}
    else {con <- DBI::dbConnect(RPostgres::Postgres(),
                                host = "localhost",
                                port = "5432",
                                user = user,
                                password = password,
                                dbname = dbname)
    }
    if (i == seconds_to_test & !db_ready) {con <- "There is no connection"}
  }
  con
}

**Comment by znmeb** [comment]
When I paged through the book this afternoon the code was there, but there was no mechanism to execute it. Since we're building the book one chapter at a time, the function would only be defined in one chapter.

**Comment by ianfrantz** [comment]
The function has been moved to here: https://github.com/smithjd/sqlpetr
