### ISSUE TITLE
Devtools for sqlpetr in 04-docker-setup-postgres

### ISSUE THREAD

**Issue by ianfrantz** [smithjd/sql-pet#108]
**Adding a chuck that an end user can run to install library: sqlpetr **

**Describe the solution you'd like**
One chunk to get the sqlpetr library.

**Comment by ianfrantz** [comment]
Preliminary code returns error. R 3.5.0 is needed.
The downloaded binary packages are in
	C:\Users\ianfr\AppData\Local\Temp\RtmpWMrPin\downloaded_packages
ERROR: this R is version 3.4.2, package 'sqlpetr' requires R >= 3.5.0

**Comment by SophieMYang** [comment]
@ianfrantz I just installed the latest of R and RStudio.  I did not do RTools.

**Comment by smithjd** [comment]
I've added instructions for installing the `sqlpetr` package to the book and the README

**Comment by ianfrantz** [comment]
Closing with merge. 

https://github.com/smithjd/sql-pet/commit/55d31570d2f0e8051ca5dd0fe56583206c02749d
