### ISSUE TITLE
Demonstrate how the Docker setup enables more / different reprexes

### ISSUE THREAD

**Issue by smithjd** [smithjd/sql-pet#11]
**Test for success.**
We started out creating an environment where a useR could test and demonstrate problems with a DBMS found inside an organization's setup but  **outside** the organization.  Have we succeeded?

**Reprex**
Show some sample **reprex** examples to demonstrate just how far we've gotten.

**Comment by znmeb** [comment]
Here's the paper by one of the creators of Rocker on the reproducible research motivations: <https://arxiv.org/abs/1410.0846>
