### ISSUE TITLE
Book builds into sql-pet/../docs, not sql-pet/docs

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#129]
The output from rendering the book is supposed to go into `sql-pet/docs`, so it can be deployed to GitHub Pages when the master branch is pushed. Instead, it's being sent into `sql-pet/../docs`.

**Comment by smithjd** [comment]
I can't understand how this crept back into our source code.  It's now corrected.

**Comment by znmeb** [comment]
Fixed ... tested
