### ISSUE TITLE
Add a .gitattributes file for line endings

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#14]
See https://help.github.com/articles/dealing-with-line-endings/. You will get mysterious failures on Windows hosts without this.

**Comment by smithjd** [comment]
@znmeb do we need to have more file types in the repo's sample?

https://github.com/smithjd/sql-pet/blob/master/.gitattributes 

Doesn't have .sh, .txt, etc.

**Comment by SophieMYang** [comment]
I saw that the .gitattributes file has been updated.  I deleted my local repo and re-cloned the sql-pet repository and was able to walk through the creation of the Postgres10 DB in  r-database-docker/04-docker-setup-postgres-connect-with-r.Rmd document.
