### ISSUE TITLE
Clean up setup instructions

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#140]
1. Simplify them so they're clean and directive
2. Add documentation for the Windows non-10-pro use case

**Comment by dpprdan** [comment]
Maybe this fits in here: I've just been browsing the book and (as a Windows user) stumbled upon Appendix E.2 which states "You will need Windows 7 64-bit or later. If you can afford it, I highly recommend upgrading to Windows 10 Pro.". Furthermore it says to install Docker for Windows stable only on Windows 10 Pro and Docker Toolbox on all other Windows versions. Maybe you can add a sentence why this is so? I.e. what is the crucial difference with Windows 10 Pro with regards to Docker?

**Comment by ianfrantz** [comment]
Thanks Daniel! 

Docker Desktop actually requires Windows 10 64bit: Pro, Enterprise or Education (1607 Anniversary Update, Build 14393 or later). - source: https://docs.docker.com/docker-for-windows/install/

Please continue to comment on our project! :)
