### ISSUE TITLE
sqlpetr package 

### ISSUE THREAD

**Issue by SophieMYang** [smithjd/sql-pet#141]
I was getting a sp_* error.  I reinstalled sqlpetr package and now received the following error message:
Quitting from lines 4-13 (13-sql_joins-and-complex-queries.Rmd) 
Error: package or namespace load failed for 'tidyverse' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called **'rlang'**
Execution halted

**Comment by SophieMYang** [comment]
steps to correct 
1.  install.packages('rlang',type='win.binary')
2.  devtools::install_github("smithjd/sqlpetr")

Not sure how rlang gets uninstalled, but I suspect it has something to do with when I tried pulling down sqlpetr.

**Comment by znmeb** [comment]
Is this still broken?

**Comment by smithjd** [comment]
I doubt it.  We don't call rlang at all in the package any more.

**Comment by znmeb** [comment]
OK ... we'll figure this all out Wednesday ;-)

**Comment by SophieMYang** [comment]
Ed,

Everything now knits after I reinstalled rlang.  Just not sure how it ever got uninstalled.
