### ISSUE TITLE
04-docker-setup. HTML on line 74

### ISSUE THREAD

**Issue by ianfrantz** [smithjd/sql-pet#144]
**HTML on line 74**

However... forcing the values still doesn't get me a connection. 

DEFAULT_POSTGRES_PASSWORD = "postgres"
> DEFAULT_POSTGRES_USER_NAME = "postgres"
> con <- sp_get_postgres_connection(user = Sys.getenv("DEFAULT_POSTGRES_USER_NAME"),
+                          password = Sys.getenv("DEFAULT_POSTGRES_PASSWORD"),
+                          dbname = "postgres",
+                          seconds_to_test = 10)

> con [1] "There is no connection"
--
 
> | >
>

**Comment by znmeb** [comment]
This is a combination of unclear documentation and unreliable initialization. Both need to be fixed.
