### ISSUE TITLE
Set up RStudio Connection tabs to work with our database

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#170]
It's possible to access the database using the "Connections" tab in RStudio. This requires some code, but I think it's worth doing. See https://rstudio.github.io/rstudio-extensions/rstudio-connections.html for the details.

**Comment by smithjd** [comment]
Provided that this doesn't involve ODBC, it would be great!  ODBC with Docker might get us into more OS-level complications...

**Comment by jimtyhurst** [comment]
I upgraded to `RStudio 1.2.1268`, a "preview" release, then experimented with the `Connections` tab to run SQL in RStudio. See the following pages for instructions:

- https://support.rstudio.com/hc/en-us/articles/115010915687
- https://db.rstudio.com/best-practices/drivers/
- https://db.rstudio.com/getting-started/connect-to-database

I needed to configure:

- DRIVERS : /usr/local/etc/odbcinst.ini
- SYSTEM DATA SOURCES : /usr/local/etc/odbc.ini
- FILE DATA SOURCES : /usr/local/etc/ODBCDataSources
- USER DATA SOURCES : /Users/jimtyhurst/.odbc.ini

I was able to connect to the 'dvdrental' db running in a Docker container for the sql-pet project.
```
-- !preview conn=DBI::dbConnect(odbc::odbc(), "PostgreSQL", timeout = 10)
SELECT * FROM "dvdrental"."public"."rental"
WHERE rental_id >= 16045
  AND rental_id <= 16049
  AND customer_id >= 100
```

**Comment by znmeb** [comment]
@jimtyhurst How did you get ODBC installed on the Mac? How authoritative is the source code? How is it maintained? On Linux, those questions don't have answers that satisfy the paranoid in me. ;-)

**Comment by jimtyhurst** [comment]
@znmeb, I performed the steps specified in the RStudio documentation:

* `brew install unixodbc` # See https://db.rstudio.com/best-practices/drivers/
    This installed the ODBC implementation from the unixODBC Project (http://www.unixodbc.org/), which is the project associated with the empty `Administrator Manual` in your screen shot. I did not use any of the manuals. I just used the RStudio documentation, although `A guide to using unixODBC without the GUI` at http://www.unixodbc.org/ had the sample connection configurations that were also shown in the RStudio documentation. I could not find the `Administrator Manual` that you referenced. I have no idea about the reliability of this ODBC driver.
* `brew install psqlodbc` # See https://db.rstudio.com/best-practices/drivers/
    This installed the official PostgreSQL ODBC driver (https://odbc.postgresql.org/)
* Created file `/usr/local/etc/odbcinst.ini` # See https://db.rstudio.com/best-practices/drivers/
* Created file `~/.odbc.ini` # See https://db.rstudio.com/best-practices/drivers/
* `install.packages("odbc")` # See https://db.rstudio.com/getting-started/connect-to-database
* Verified the ODBC connection configurations were accessible by RStudio:
    ```
    library(odbc)
    sort(unique(odbcListDrivers()[[1]]))
    ```
* In RStudio, `Connections > + Connection` to create a new connection for PostgreSQL in the `Connections` tab.
* In RStudio, `File > New File... > SQL Script` to create a new source file. I revised the default connection string to: `conn=DBI::dbConnect(odbc::odbc(), "PostgreSQL", timeout = 10)`. Then revised the default SQL code to select from the `rental` table.

**Comment by znmeb** [comment]
OK - that should work on Linux - do you need to be `root` to install it on a Mac?

**Comment by jimtyhurst** [comment]
`brew` installs do not require using `sudo` on Mac, so I went through the different installations with my own userid.

**Comment by znmeb** [comment]
I have it working on Arch Linux with a dataset name. The other way - entering the connection parameters in the dialog box - doesn't seem to work yet. There's no usable documentation for that option as far as I can tell; it appears to be defaulting to the "Unix socket" connection scheme.

If we're going to use the connection tab we can implement the `connection contract` in `sqlpetr` using the `odbc` package as a template. See <https://rstudio.github.io/rstudio-extensions/connections-contract.html> and <https://github.com/r-dbi/odbc/blob/master/R/Viewer.R>.
