### ISSUE TITLE
Remove Python stuff

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#22]
Miniconda, reticulate, installr and the R `docker` package ... we don't need them.

**Comment by jimtyhurst** [comment]
I agree that for the purposes of this tutorial, focusing on using R to access a SQL database, it works well to have one Docker image that has a PostgreSQL database _and_ some data all in one image that can be used with Docker and does not need Docker Compose.

**Comment by znmeb** [comment]
@jimtyhurst My current thinking is that we should have two or possibly three images - PostgreSQL, Rocker / RStudio Server and maybe pgAdmin4. That would be my bare minimum toolset.

**Comment by znmeb** [comment]
@smithjd This is done, isn't it? Can we close it?
