### ISSUE TITLE
Document how to edit the bookdown files.

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#24]
We probably need a separate document for this. I've built this mostly with the defaults, so it should mostly be a matter of making sure everyone can branch the repo, write a chapter, build the book and submit a pull request when they're ready.

**Comment by smithjd** [comment]
Capturing what Ed posted in Slack:

* You'll need RStudio and the `bookdown` package.
* To make changes, branch or fork the repo.
* Open the RStudio project file in `r-database-docker`, **not the top folder!**
* You can edit a page in the code editor, then save it and press the `Knit` button till you're satisfied with the text.

For our first exercise Ed suggests:

1. Clone the repo
2. Open the project
3. Create a branch
4. Edit `index.Rmd` and add your bigography
5. Go to the `Build` tab and `Build Book`.
6. Sandard sequence of `Commit`, `Push`, `Merge`, etc.

**Comment by znmeb** [comment]
To build the book for deployment, you have to run the `build_book.R` script. The Build Book tab is fine for editing, but it doesn't clean out the old files - the script does.

**Comment by smithjd** [comment]
OK, did that for the `goals` branch and updated our thumbnail instructions here...

**Comment by znmeb** [comment]
Done
