### ISSUE TITLE
Document running the "rocker/rstudio" image

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#25]
The more I think about this, the more I'm coming to the conclusion we ought to be running a two-container Docker network - PostgreSQL from the standard image and Rocker RStudio (<https://hub.docker.com/r/rocker/rstudio/>). That way, we only have a dependency on a browser and Docker hosting.

I'd also throw in the pgAdmin4 image (<https://hub.docker.com/r/dpage/pgadmin4/>) - it's hard for me to imagine doing serious PostgreSQL without pgAdmin4.

**Comment by scottcame** [comment]
This is a good idea. I think this would get us back into docker-compose territory, no?  I mean, you could accomplish the same by starting up all the containers and creating the bridge network with individual docker commands, but...it'd be better to document all of that in a compose file...
