### ISSUE TITLE
Documentation and executable code in different directories & Rstudio projects

### ISSUE THREAD

**Issue by smithjd** [smithjd/sql-pet#26]
**I'm concerned that we'll have Rmarkdown problems** if the default directory for the Documentation project and the SQL-Pet project are not the same.

**Proposed solution**
Move the documentation folder up to be the same as its parent directory.  It would make the project an "executable training" project

**Rmarkdown problems**
As I understand it Rmarkdown is very finicky about what it's working directory is.  I think we might find ourselves creating a lot of problems if we keep the 2 directories separate.

**Comment by znmeb** [comment]
https://www.tidyverse.org/articles/2017/12/workflow-vs-script/

**Comment by smithjd** [comment]
I will remove the .src directory and the files it contains.  After the book is done we can selectively add things back in if needed.
