### ISSUE TITLE
Making dvdrental database more "realistic" -- challenging with "bad data"

### ISSUE THREAD

**Issue by smithjd** [smithjd/sql-pet#30]
**How realistic is dvdrental?**
Real live data usually has all kinds of vestigial junk that we have to figure out and accommodate in our explorations and analyses.

**Edit the data and insert some real live problems**
We could add or subtract records or otherwise distort the database.  That would result in 2 versions --`original dvdrental` and `dvdrental *enhanced*`.  :-)

**Alternatives**
* Provide a script that introduces random or systematic error
* Skip the whole idea and keep it as simple as possible

**Additional context**
Your mileage may vary.  Maybe you are blessed with clean data or maybe you just pretend that you are blessed.  :-)

**Comment by znmeb** [comment]
I'd be careful with this. As any DBA knows, a big part of the job is insuring data quality. If R can make a contribution to this activity in a form usable by the DBA, great. Otherwise you might just end up irritating the DBA. ;-)
