### ISSUE TITLE
Password in plaintext

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#5]
**Describe the bug**
The database superuser `postgres` password is specified in plaintext. It should be specified in an environment variable.

**To Reproduce**
1. Clone this repo
2. Edit `docker-compose.yml`.
3. `POSTGRES_PASSWORD` is defined in plaintext

**Expected behavior**
The password value should be a reference to an environment variable stored in a `.env` file which is ***not*** maintained in version control.

**Additional context**
The Docker documentation on maintaining secrets is, in a word, terrible. And to make matters worse, it's deployment-specific - it's different for Amazon Web Services, Docker Swarm, Kubernetes or a simple desktop install like we have here.

**Comment by smithjd** [comment]
I think we need to make the issue of password specification on the Docker and the R sides really visible.  In fact we want to **show** password problems, right?  Maybe the topic deserves a separate script that addresses password issues in all the different environments and shows what **not** to do as well as how to do it right.

**Comment by znmeb** [comment]
"There are three kinds of men. The one that learns by reading. The few who learn by observation. The rest of them have to pee on the electric fence for themselves." - Will Rogers ;-)

What we did for Hack Oregon deployment was Amazon Web Services specific. For the desktop development environment, we created an `env.sample` file with values, and instructed the user to copy that to `.env` and then edit it to change the passwords. `.env` is the default file for Docker Compose environment variables and it needs to be flagged in `.gitignore` so it doesn't end up in the public repository!

However, as you might guess, given the issues with Docker Compose, I think we should migrate to raw Docker commands driven by R scripts. That would mean using the R `keyring` package to manage all the secrets / API keys, etc. That's the path I'm going down for my transit nerd and daily fantasy sports packages.

**Comment by smithjd** [comment]
I wonder whether switching from a system() / system2() strategy for interacting with Docker to using the Docker package would move us forward and / or bypass some of the pesky platform differences?  Looking at:  https://cran.r-project.org/web/packages/docker/vignettes/Getting_Started_with_Docker.html

**Comment by znmeb** [comment]
I like that idea - one potential gotcha though. `virtualenv` doesn't exist on Windows - you have to have `conda`. `reticulate` can work with either, but we might need to fork the `docker` repo and modify the code to test for Windows and use `conda`.

Let me hunt around for an R package that talks to the Docker API directly - there must be something.

**Comment by smithjd** [comment]
We need a little tutorial that talks about passwords on the R side as well as on the Docker setup side.

**Comment by smithjd** [comment]
Here are a bunch of resources about managing credentials.  https://db.rstudio.com/best-practices/managing-credentials/

**Comment by jimtyhurst** [comment]
The original problem, `POSTGRES_PASSWORD` is defined in plaintext no longer exists, because there is no longer a `docker-compose.yml` file. There are two ways to avoid this problem in the future:
1. As @znmeb mentioned in the description, maintain the password in a file that is not stored in the source repository. Then each developer and student is instructed how to set up such a file.
2. Set an operating system level environment variable that is referenced by scripts. Again, developers and students need to be instructed how to do that for different development and deployment platforms.

Often (2) is just a special case of (1), because the easiest way to accomplish (2) is to have a script that sets environment variables in an operating system shell.
