### ISSUE TITLE
Use the project `Wiki` for documentation about the project, like `Meeting Notes`

### ISSUE THREAD

**Issue by jimtyhurst** [smithjd/sql-pet#53]
I am requesting that someone with write-access to the repository should activate the `Wiki` as an additional place to store information about the `sql-pet` project.

**Is your feature request related to a problem? Please describe.**
Project metadata can get scattered easily to various locations on the web, because people use the best tool at the moment to generate that metadata. However, it is more convenient to find metadata when it is all located within the GitHub "project".

**Describe the solution you'd like**
The `sql-pet` project is currently using most of the GitHub tools that are available:
* Tasks in the project kanbans.
* News and essential set-up instructions in the `README.md` file.
* Tutorial documentation in Bookdown and corresponding published site: https://smithjd.github.io/sql-pet/

However, the `Wiki` has not yet been activated and that is an excellent place for additional metadata that does not fit in the locations in the bullet list above. For example, in the development meeting today, a [Meeting Notes](https://docs.google.com/document/d/1e3pqz0XhB1ZB1jWFxHLI3mPb66xOtj6opUBGV2qNON0/) file was opened up as a Google Doc to allow participants to take notes simultaneously in one central location. Now that the meeting is over and it is no longer necessary for people to update the document simultaneously, it could/should be added to the `Wiki` for future reference.

**Describe alternatives you've considered**
Someone in the meeting suggested putting the notes in a `Note` object in the project's [kanban](https://github.com/smithjd/sql-pet/projects/1), but `Note` objects have a fairly limited maximum number of characters that are allowed, which make them less than ideal for representing an arbitrary length document-like object, like meeting notes. I do not know the exact size limitations on a `Note`, but from another project, I have observed the limitation when I tried to use them for review comments.

**Additional context**
I do not have `Collaborator` write privileges in the [sql-pet](https://github.com/smithjd/sql-pet/) repository, otherwise I would have activated the `Wiki` myself and copied the [Meeting Notes](https://docs.google.com/document/d/1e3pqz0XhB1ZB1jWFxHLI3mPb66xOtj6opUBGV2qNON0/edit) there.

**Comment by smithjd** [comment]
Makes a lot of sense to me, Jim.  It looks to me like the wiki is enabled.  I clicked on the Wiki button above, and created a default page.

**Comment by znmeb** [comment]
Yeah - I have wiki too. Maybe @jimtyhurst isn't in the collaborator list?

BTW, I'm not a huge fan of GitHub wikis. It's mostly a matter of having to look multiple places for documentation.

**Comment by jimtyhurst** [comment]
I am now a contributor, so I now have write-rights to the Wiki. I created a couple of pages with links to the project documentation, including yesterday's meeting notes.
