### ISSUE TITLE
library install instructions

### ISSUE THREAD

**Issue by maryannet** [smithjd/sql-pet#70]
04-docker-setup-postgres line 3 to 8 needs install instructions if you do not have library

**Comment by jimtyhurst** [comment]
I agree with @znmeb that having a script to load all dependencies is a good idea. I will also mention that if we had this project set up as a package, that would happen automatically when someone loaded the package. That is one of the advantages of developing with a package structure even when you know you will never submit it to some package repository, like CRAN.

**Comment by znmeb** [comment]
@jimtyhurst I think we should start building the package now - we've got three weeks till the next meeting. I'll post this here for those who are new to it: http://r-pkgs.had.co.nz/

This is a pre-bookdown book so it's got a different format but it's good and it's free.
