### ISSUE TITLE
Can't knit "05-docker-setup-postgres-with-dvdrental.Rmd" - duplicate chunk label

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#71]
An attempted `knit` of `05-docker-setup-postgres-with-dvdrental.Rmd` crashes thusly:

```
==> rmarkdown::render_site('/home/znmeb/Projects/sql-pet/r-database-docker/05-docker-setup-postgres-with-dvdrental.Rmd',  encoding = 'UTF-8');


processing file: r-database-docker.Rmd
Error in parse_block(g[-1], g[1], params.src) : duplicate label 'setup'
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted
```

**Comment by smithjd** [comment]
The `r-database-docker.Rmd` is left there when there is some other problem in knitting the whole book.  It should be deleted whenever it is found.  After that the book will compile correctly.

**Comment by znmeb** [comment]
Yeah, I found that out. But it's not just `r-database-docker.Rmd` - there are other things going on here.
