### ISSUE TITLE
/docs directory clutters the git repository with redundant text, code, and data

### ISSUE THREAD

**Issue by jimtyhurst** [smithjd/sql-pet#78]
**Is your feature request related to a problem? Please describe.**
_Expected structure_:
Source code repositories only contain source code. Files that are constructed through a build process are not usually stored in a git repository.

_Actual structure_:
The `sql-pet` project directory has a `/docs` directory that is generated by the Bookdown build process.

**Problems caused by the current approach**
1. The constructed files in `/docs` get out of synch with the source files in `/r-database-docker` when someone changes the source files, but does not re-knit the book.
2. There is no automated build process or automated audit to make sure that the two directories are synchronized.
3. When someone does make changes and re-knit the book, their Pull Request has a lot of clutter, because the same changes appear in the source files and in the build output.

**Describe the solution you'd like**
1. Remove the `/docs` directory from the `sql-pet` project directory structure. 
2. Add an explanation to the `README.md`, describing how to generate the book. Better yet, provide an `init.sh` script that a student should run when they first clone the repository.

**Describe alternatives you've considered**
Another possibility is to have an automated Continuous Integration (CI) build process that generates `/docs` every time that changes are made in `/r-database-docker`. But that only solves one of the problems caused by storing build output files in the source repository.

**Comment by znmeb** [comment]
The docs directory is where the book is deployed via GitHub Pages. There are quite a few options to choose from for deploying the book:

1. Move from the `docs` folder in the repo to a `gh-pages` ***branch*** in the repo.
2. Make another repo for the book but leave it on GitHub Pages.
3. Deploy it to `bookdown.org`. This is a one-click operation in RStudio, if I remember correctly, and probably makes the most sense given the nature of this project.
4. Deploy to Netlify. That's a bit tricky; it used to be very simple but Netlify has tacked on a lot of infrastructure that's opinionated in a number of ways.

My recommendation is moving to Bookdown.org.

**Comment by znmeb** [comment]
I'm getting frustrated reviewing pull requests and seeing mountains of changes in the HTML files for the book. I just want to review source code, not artifacts of the publishing process.

I'm not sure how to set this up - let me think about it overnight. I'll post something in the Slack when I get some ideas.
