### ISSUE TITLE
Working Directory Issues of Windows VS Mac

### ISSUE THREAD

**Issue by ianfrantz** [smithjd/sql-pet#81]
**Bug in: 05-docker-setup-postgres-with-dvdrental.Rmd**
Line 72-73: The source parameter contains two apostrophes. This causes an invalid mount path on windows. `invalid mount path: ''C:/Users/ianfr/Desktop/R_Programs/sql-pet/r-database-docker/'' mount path must be absolute."`

**To Fix** 
These apostrophes must be removed but this may impact the Mac OS users. I suspect the problem starts on line 63 `wd <- getwd()`. Perhaps we want to look at what parameters are available to standardize how R reads the wd into it's namespace. 

**To Reproduce**
1. Open: 05-docker-setup-postgres-with-dvdrental.Rmd
2. GoTo: Line 65 - setting up docker_cmd with glue
3. Windows output:
`run --detach  --name sql-pet --publish 5432:5432 --mount type=bind,source='C:/Users/ianfr/Desktop/R_Programs/sql-pet/r-database-docker/',target=/petdir postgres-dvdrental`
4. Notice how source is single quoted in the docker_cmd. 
5. Source becomes double quoted in the execution phase. `''C:/Users/ianfr/Desktop/R_Programs/sql-pet/r-database-docker/''`

**Comment by smithjd** [comment]
Note that at least single-quoting is probably needed for safety because there *may* be spaces in a directory name that will mess up the `source` parameter if it isn't quoted.

**Comment by SophieMYang** [comment]
Here is the updated code block.  It still needs to be cleaned up.  To make a directory in Windows, one needs to double quote the directory name.  

I initially tried creating a directory as 'r database docker' on my machine and I got three directories, 'r, database, and docker'.  I successfully created the directory with double quotes as "r database docker".  I then copied everything from r-database-docker into "r database docker".

I overwrote wd  
       wd <- getwd()
      wd <- '"C:/Git/sql-pet/r database docker"'  #works
and used the source and wd without the single quote.  
     "source=", # tells Docker where the local file will be found
      wd, "/,", # the current working directory, as retrieved above
and it worked.  

I removed the sql-pet container and then overrode the source/wd parameters switching the role of the single and double quote.  The container was created.
       "source='", # tells Docker where the local file will be found
       wd, "/',", # the current working directory, as retrieved above
       'source="', # tells Docker where the local file will be found
       wd, '/",', # the current working directory, as retrieved above

Ian:  Here is the updated script.  Please confirm it works as advertised.  I left both versions in the script for now to show both forms.  I can clean the code up or 

wd <- getwd()
#wd <- '"C:/Git/sql-pet/r database docker"'  #works

docker_cmd <- glue(
  "run ",      # Run is the Docker command.  Everything that follows are `run` parameters.
  "--detach ", # (or `-d`) tells Docker to disconnect from the terminal / program issuing the command
  " --name sql-pet ",     # tells Docker to give the container a name: `sql-pet`
  "--publish 5432:5432 ", # tells Docker to expose the Postgres port 5432 to the local network with 5432
  "--mount ", # tells Docker to mount a volume -- mapping Docker's internal file structure to the host file structure
  "type=bind,", # tells Docker that the mount command points to an actual file on the host system
  "source='", # tells Docker where the local file will be found
  wd, "/',", # the current working directory, as retrieved above
  'source="', # tells Docker where the local file will be found
  wd, '/",', # the current working directory, as retrieved above

  "target=/petdir", # tells Docker to refer to the current directory as "/petdir" in its file system
  " postgres-dvdrental" # tells Docker to run the image was built in the previous step
)
# if you are curious you can paste this string into a terminal window after the command 'docker':
print('')
wd
print(glue('docker ',docker_cmd))

system2("docker", docker_cmd, stdout = TRUE, stderr = TRUE)


**Here is the output I get**.
print(glue('docker ',docker_cmd))
docker run --detach  --name sql-pet --publish 5432:5432 --mount type=bind,source='"C:/Git/sql-pet/r database docker"/',source="C:/Git/sql-pet/r database docker"/,target=/petdir postgres-dvdrental
> 
> system2("docker", docker_cmd, stdout = TRUE, stderr = TRUE)
[1] "611ba02e2974ecdb8f77a29e6baff698a17f9aa7760700afc139df137b5f41df"

**Comment by SophieMYang** [comment]
An advance SQL topic discussed either at the last meeting or lunch was explain plans which I did not see in your outline.  I also started added timings to the code blocks to compare and contrast SQL pushdown versus Dplyr SQL.  Don't want those DBA's to come looking you up.  Another one just popped into my head, DB privileges.  This is important if you want to create staging tables in the DB.

**Comment by SophieMYang** [comment]
@smithjd: these two lines should have start and end with a single quote ' as shown in the next two lines.
       'source="', # tells Docker where the local file will be found
       wd, '/",', # the current working directory, as retrieved above
This is what I see in the repo, the two lines start with a double quote.
      "source='", # tells Docker where the local file will be found
       wd, "/',", # the current working directory, as retrieved above

**Comment by smithjd** [comment]
That's basically what I've got:

` 'type=bind,source="', wd, '/",target=/petdir',`

Are you suggesting that `type`, `source`, `target` should all be separated out?  I've left them in one undifferentiated chunk, not being clear that we have something useful to say about each of those parts.

**Comment by SophieMYang** [comment]
Where is the new code?  I just checked the repo main branch and do not  see the  code in your previous comment, but see my comment.

**Comment by smithjd** [comment]
https://github.com/smithjd/sql-pet/blob/master/r-database-docker/06-docker-setup-postgres-with-dvdrental-piecemeal.Rmd

**Comment by SophieMYang** [comment]
that explains it.  I pulled up 05.  Another error between the keyboard and the chair.

**Comment by smithjd** [comment]
oops. are we talking about different files?  Let me take a crack at the `-05` file. It needs fixing, too.

**Comment by smithjd** [comment]
OK, I fixed the `05-` file, too.

**Comment by SophieMYang** [comment]
Is the focus of the SQL section to focus on similarities/differences between SQL and dbplyr approach with emphasis on where the heavy lifting occurs, in the DB or the laptop?  Eventual do we want to have a section where a medium size set of table get loaded up in the DB to give a more realistic context to the user?

**Comment by smithjd** [comment]
Hmm.  You're making sense.  (But I think you should add something here:

`https://github.com/smithjd/sql-pet/wiki/Pathway-for-SQL-instruction`

rather than in this discussion... right?

**Comment by SophieMYang** [comment]
I'll check the link.  I was just going to prototype both approaches.  

Since my branch has been merged, shouldn't it be removed?  I am about to pull the latest and greatest.

**Comment by smithjd** [comment]
Better wait on that. I think I still have a couple of follow-ups from points you made in another discussion.  I'll remove it when I'm sure I've captured all the goodies you put i the hopper.

In the meantime, I think you can build off of `master`...

**Comment by znmeb** [comment]
Is this fixed?
