### ISSUE TITLE
Document Windows Docker hosting

### ISSUE THREAD

**Issue by znmeb** [smithjd/sql-pet#9]
**Is your feature request related to a problem? Please describe.**
We need documentation for Windows Docker hosting

**Describe the solution you'd like**
Steps for setting up Windows Docker hosting on Windows

**Comment by znmeb** [comment]
In progress at <https://github.com/smithjd/sql-pet/blob/master/docker_hosting_for_windows.md> ... comments welcome!!

**Comment by znmeb** [comment]
Next up - document the `docker` R package interface. This requires Miniconda, which is documented as of 2018-08-31

**Comment by ianfrantz** [comment]
I haven't seen where we are using anything from this library yet.
