### ISSUE TITLE
Suggestion: Use fully qualified function names

### ISSUE THREAD

**Issue by jimtyhurst** [smithjd/sql-pet#93]
**Is your feature request related to a problem? Please describe.**
There are quite a few packages mentioned in the tutorial. Some of them are likely to be new to the people taking the tutorial. When a new function is used, it is difficult to know where it is defined.

**Describe the solution you'd like**
I suggest using the package name as a prefix, which makes it very clear where the function is defined. For example, rather than:
```
    columns_info_schema_table <- tbl(con, in_schema("information_schema", "columns"))
```
use:
```
    columns_info_schema_table <- dplyr::tbl(con, dbplyr::in_schema("information_schema", "columns")) 
```
at least for the first couple times that a function appears in the tutorial.

**Describe alternatives you've considered**
Of course, a student can always get help at the command line to find the package to which a function belongs. For example,
```
    > ?in_schema
```
but I think it is easier for the student and more clear when the package names are used as a prefix.

**Additional context**
Some functions appear in more than one package, which makes it even more confusing for the student when the function name is not fully specified with its package name. For example, `kable` is defined in `knitr` and `skimr`.

**Comment by smithjd** [comment]
This is a very good idea...   the list of packages we're using seems to keep growing.  Currently it includes:

  * DBI
  * dbplyr
  * DiagrammeR
  * downloader
  * getPass
  * glue
  * here
  * knitr
  * RPostgres
  * rstudioapi
  * skimr
  * tidyverse

**Comment by smithjd** [comment]
I've started a Style Guide on the wiki: https://github.com/smithjd/sql-pet/wiki/Style-guide

**Comment by smithjd** [comment]
This is definitely good practice.  Let's flag individual violations!
